/*
Enter your query here.
Please append a semicolon ";" at the end of the query and enter your query in a single line to avoid error.
*/

/*
DECLARE @MAXSALARY INT
DECLARE @NUMMAXEMPLOYEES INT
SELECT @MAXSALARY = MAX(MONTHS * SALARY) FROM EMPLOYEE;
SELECT @NUMMAXEMPLOYEES = COUNT(EMPLOYEE_ID) FROM EMPLOYEE WHERE (MONTHS*SALARY) = @MAXSALARY;
SELECT @MAXSALARY, @NUMMAXEMPLOYEES;
*/

SELECT TOP 1
    (MONTHS*SALARY),
    COUNT(EMPLOYEE_ID)
FROM
    EMPLOYEE
GROUP BY
    (MONTHS*SALARY)
ORDER BY
    (MONTHS*SALARY) DESC

/*  
SELECT 
    MAX(MONTHS * SALARY),
    COUNT(EMPLOYEE_ID)
FROM 
    EMPLOYEE
GROUP BY
    EMPLOYEE_ID
*/

